# Generated by Django 5.2.3 on 2025-10-14 14:23

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('floors_total', models.IntegerField()),
                ('wall_material', models.CharField(blank=True, max_length=100)),
                ('construction_year', models.PositiveIntegerField(blank=True, null=True)),
                ('house_amenities', models.CharField(blank=True, max_length=255)),
                ('parking', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='IDS',
            fields=[
                ('apartment_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(verbose_name='Статус')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district', models.CharField(blank=True, max_length=255)),
                ('microdistrict', models.CharField(blank=True, max_length=255)),
                ('street', models.CharField(blank=True, max_length=100, null=True)),
                ('house_number', models.CharField(blank=True, max_length=255, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Region')),
            ],
        ),
        migrations.CreateModel(
            name='Apartment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(default='Buy Apartment')),
                ('price', models.FloatField()),
                ('total_area', models.FloatField()),
                ('living_area', models.FloatField()),
                ('kitchen_area', models.FloatField(blank=True, null=True)),
                ('balcony_area', models.FloatField(blank=True, null=True)),
                ('balcony', models.CharField(blank=True, choices=[('No', 'No'), ('Classic', 'Classic'), ('French', 'French'), ('Extended', 'Extended'), ('Loggia', 'Loggia')], default='No', null=True)),
                ('room_count', models.IntegerField()),
                ('description', models.TextField(blank=True, null=True)),
                ('floor', models.IntegerField()),
                ('sale_conditions', models.CharField(choices=[('Alternative', 'Alternative Sale'), ('Open', 'Open Sale'), ('Condition', 'Conditional Sale')], default='Open', max_length=20)),
                ('bathroom_count', models.IntegerField(blank=True, null=True)),
                ('ceiling_height', models.FloatField(blank=True, null=True)),
                ('renovation', models.CharField(blank=True, max_length=100)),
                ('condition', models.CharField(blank=True, choices=[('New', 'New'), ('Almost', 'Almost New'), ('Good', 'Good'), ('Fair', 'Fair'), ('Renovation', 'Needs Renovation'), ('Uninhabitable', 'Uninhabitable')], default='New', max_length=20)),
                ('contract_number', models.CharField(blank=True, max_length=255)),
                ('contract_date', models.DateTimeField(blank=True, null=True)),
                ('level_count', models.IntegerField(blank=True, null=True)),
                ('ownership_type', models.CharField(blank=True, choices=[('State', 'State Owned'), ('Private', 'Private'), ('Shared', 'Shared Ownership'), ('Joint', 'Joint Ownership'), ('Collective', 'Collective Ownership'), ('Foreign', 'Foreign')], default='Private', max_length=20)),
                ('link', models.CharField(blank=True, max_length=100, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apartments', to=settings.AUTH_USER_MODEL)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apartments', to='apartments.building')),
            ],
        ),
        migrations.CreateModel(
            name='ApartmentImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='apartments_images/')),
                ('apartment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='apartments.apartment')),
            ],
        ),
        migrations.AddField(
            model_name='building',
            name='location',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='building', to='apartments.location'),
        ),
        migrations.CreateModel(
            name='Town',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Town')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='towns', to='apartments.region')),
            ],
        ),
        migrations.AddField(
            model_name='location',
            name='town',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='apartments.town'),
        ),
    ]
