# Generated by Django 5.2.3 on 2025-10-15 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='location',
            index=models.Index(fields=['town', 'street', 'house_number'], name='apartments__town_id_cdeaf0_idx'),
        ),
        migrations.AddConstraint(
            model_name='location',
            constraint=models.UniqueConstraint(fields=('town', 'district', 'microdistrict', 'street', 'house_number'), name='uq_location_full_address'),
        ),
        migrations.AddConstraint(
            model_name='town',
            constraint=models.UniqueConstraint(fields=('region', 'name'), name='uq_town_region_name'),
        ),
    ]
