# Generated by Django 5.2.3 on 2025-07-30 14:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0002_apartmentimage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='apartment',
            options={},
        ),
        migrations.AlterModelOptions(
            name='building',
            options={},
        ),
        migrations.AlterModelOptions(
            name='location',
            options={},
        ),
        migrations.AlterModelOptions(
            name='region',
            options={},
        ),
        migrations.AlterModelOptions(
            name='town',
            options={},
        ),
        migrations.AddField(
            model_name='apartment',
            name='link',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='balcony',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='balcony_area',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='balcony_type',
            field=models.CharField(blank=True, choices=[('Classic', 'Classic'), ('French', 'French'), ('Extended', 'Extended'), ('Loggia', 'Loggia')], default=None, null=True),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='bathroom_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='building',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apartments', to='apartments.building'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='ceiling_height',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='condition',
            field=models.CharField(blank=True, choices=[('New', 'New'), ('Almost', 'Almost New'), ('Good', 'Good'), ('Fair', 'Fair'), ('Renovation', 'Needs Renovation'), ('Uninhabitable', 'Uninhabitable')], default='New', max_length=20),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='contract_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='contract_number',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='floor',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='kitchen_area',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='level_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='living_area',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apartments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='ownership_type',
            field=models.CharField(blank=True, choices=[('State', 'State Owned'), ('Private', 'Private'), ('Shared', 'Shared Ownership'), ('Joint', 'Joint Ownership'), ('Collective', 'Collective Ownership'), ('Foreign', 'Foreign')], default='Private', max_length=20),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='renovation',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='room_count',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='sale_conditions',
            field=models.CharField(choices=[('Alternative', 'Alternative Sale'), ('Open', 'Open Sale'), ('Condition', 'Conditional Sale')], default='Open', max_length=20),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='title',
            field=models.CharField(default='Buy Apartment'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='total_area',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='apartmentimage',
            name='apartment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='apartments.apartment'),
        ),
        migrations.AlterField(
            model_name='apartmentimage',
            name='image',
            field=models.ImageField(upload_to='apartments_images/'),
        ),
        migrations.AlterField(
            model_name='building',
            name='construction_year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='building',
            name='floors_total',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='building',
            name='house_amenities',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='building',
            name='location',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='building', to='apartments.location'),
        ),
        migrations.AlterField(
            model_name='building',
            name='parking',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='building',
            name='wall_material',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='location',
            name='district',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='location',
            name='house_number',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='location',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='microdistrict',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='location',
            name='street',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='location',
            name='town',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='apartments.town'),
        ),
        migrations.AlterField(
            model_name='region',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Region'),
        ),
        migrations.AlterField(
            model_name='town',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Town'),
        ),
        migrations.AlterField(
            model_name='town',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='towns', to='apartments.region'),
        ),
    ]
