# Generated by Django 5.2.3 on 2025-07-30 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0003_alter_apartment_options_alter_building_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apartment',
            name='balcony_type',
        ),
        migrations.AlterField(
            model_name='apartment',
            name='balcony',
            field=models.CharField(blank=True, choices=[('No', 'No'), ('Classic', 'Classic'), ('French', 'French'), ('Extended', 'Extended'), ('Loggia', 'Loggia')], default='No', null=True),
        ),
    ]
