# Generated by Django 5.2.3 on 2025-08-04 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0004_remove_apartment_balcony_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='house_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='street',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
