# Generated by Django 5.2.3 on 2025-08-13 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0005_alter_location_house_number_alter_location_street'),
    ]

    operations = [
        migrations.CreateModel(
            name='IDS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apartment_id', models.IntegerField(verbose_name='Монго id')),
                ('status', models.CharField(verbose_name='Статус')),
            ],
        ),
    ]
