# Generated by Django 5.2.3 on 2025-09-03 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0006_ids'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
