# Generated by Django 5.2.3 on 2025-10-20 11:52

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('apartments', '0002_location_apartments__town_id_cdeaf0_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IDS',
            fields=[
                ('rent_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='Rent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(default='Rent apartments')),
                ('price', models.FloatField()),
                ('total_area', models.FloatField()),
                ('living_area', models.FloatField()),
                ('kitchen_area', models.FloatField(blank=True, null=True)),
                ('balcony', models.BooleanField(default=False)),
                ('floor', models.IntegerField()),
                ('description', models.TextField(blank=True, null=True)),
                ('room_count', models.PositiveIntegerField(blank=True, null=True)),
                ('separate_rooms', models.PositiveIntegerField(blank=True, null=True)),
                ('renovation', models.CharField(blank=True, max_length=100, null=True)),
                ('furniture', models.BooleanField(default=True)),
                ('bathroom', models.CharField(blank=True, max_length=100, null=True)),
                ('quarter', models.FloatField(blank=True, null=True)),
                ('term_of_rent', models.CharField(blank=True, max_length=100, null=True)),
                ('contract_number', models.CharField(blank=True, max_length=100, null=True)),
                ('rent_conditions', models.CharField(blank=True, max_length=100, null=True)),
                ('prepayment', models.CharField(blank=True, max_length=100, null=True)),
                ('parking', models.BooleanField(default=False)),
                ('layout', models.CharField(blank=True, max_length=100, null=True)),
                ('link', models.CharField(blank=True, max_length=100, null=True)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rents', to='apartments.building')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rents', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RentImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='rent_images/')),
                ('apartment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='rent.rent')),
            ],
        ),
    ]
